### PR TITLE
install: Dont quote number vars, to support older bash versions

### LINKED ISSUE #1861: When installing an error is given
## Expected Behavior

The installation should happen without any issue

## Current Behavior

When running the installation, an error is given:
`install.sh: line 174: "2" - 1: syntax error: operand expected (error token is ""2" - 1")`

## Steps to Reproduce

1. git clone --depth=1 https://github.com/Bash-it/bash-it.git
2. cd bash-it
3. ./install.sh

## Your Environment

* Bash-it version used: master branch
* Bash version: 4.2.46
* Operating System and version: Amazon Linux 2

## Your Bash Config File

```bash
  # Your bash config file should be here
```

### PR DESCRIPTION
**Pull request by NoahGorny**
## Description

Dont quote number vars, to support older bash versions

## Motivation and Context

Closes #1861

## How Has This Been Tested?

Locally, with a docker image of an older bash and my machine

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -171,7 +171,10 @@ while getopts "hsinaf" opt; do
 			;;
 	esac
 done
-shift $(("$OPTIND" - 1))
+
+# If we quote here, this will not work on older versions of bash
+# shellcheck disable=2004
+shift $(($OPTIND - 1))
```
Comment (davidpfarrell) [inline install.sh:177]: I think [shellcheck SC2004](https://github.com/koalaman/shellcheck/wiki/SC2004) wants:
```
shift $((OPTIND - 1))
```

With this, you should be able to remove the disable statement

Comment (NoahGorny) [reply install.sh]: nice one @davidpfarrell, done :smile:

**Review by davidpfarrell — APPROVED** [review]
Interesting that shellcheck didn't flag `"$OPTIND"` version
