### PR TITLE
Glob for *.bash properly when path contains spaces

### LINKED ISSUE #1435: BASH_IT_CUSTOM doesn't work without setting bash globstar option
Setup:
Setting BASH_IT_CUSTOM in my .bashrc prior to source bash_it.sh 
e.g. `export BASH_IT_CUSTOM=/home/foo/bash_it_custom`

These files are not loaded unless I set globstar option in bash prior to loading bash_it.sh.  Looking at the code it appears that it is using a "**" which requires the globstar option for evaluation.

`bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
`

### PR DESCRIPTION
**Pull request by gaelicWizard**
## Description
Instead of $LIB and $CUSTOM variables, use the glob pattern in the foreach statement quoting the path but not the glob. Quoting the glob will make it not a glob, but when expanding the not-quoted $LIB or $CUSTOM variable Bash will split all words, including spaces in the actual path. This helps towards #1696.

This is literally one of the examples under Code Style on the contribution page.

Closes #1435.

## Motivation and Context
This resolves the failure to source the files under $BASH_IT/lib when there is any space in $BASH_IT, such as when the user name contains a space or the path to the repository contains a space.

You can reproduce this with a user short name with a space, which is possible with the "MacBuddy" default setup assistant on Mac OS X, or if $BASH_IT is set to a path containing an (additional) space, like if I cloned to ~/Library/Application Support/Bash It. Windows commonly has user names with spaces. 

## How Has This Been Tested?
This is my current working branch since July on my system where $BASH_IT is ~/Library/Application Support/Bash It (that's two spaces in the path).

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [x] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Review by davidpfarrell — DISMISSED** [review]
Greetings - Thanks for taking the time to debug and create a PR, as well as the thorough description of the issue !

I've confirmed the issue (and fix) locally.

I have a small suggestion to keep the `CUSTOM` variable so we only have to do the complex definition once.

File: bash_it.sh [hunk 1]
```diff
@@ -109,8 +108,7 @@ done
 # Custom
 BASH_IT_LOG_PREFIX="core: main: "
 _log_debug "Loading general custom files..."
-CUSTOM="${BASH_IT_CUSTOM:=${BASH_IT}/custom}/*.bash ${BASH_IT_CUSTOM:=${BASH_IT}/custom}/**/*.bash"
-for _bash_it_config_file in $CUSTOM; do
+for _bash_it_config_file in "${BASH_IT_CUSTOM:=${BASH_IT}/custom}"/*.bash "${BASH_IT_CUSTOM:=${BASH_IT}/custom}"/**/*.bash; do
```
[the remark this answers is not in the document]
Comment (gaelicWizard) [reply bash_it.sh:111]: Using the $CUSTOM variable as it was causes the problem that this patch fixes, but an alternative might work. I'll try it out. I've alsö found the same problem when enabling a plugin, so I'm working on that too.

**Comment by gaelicWizard** [comment]
After just force-pushing twice, I remembered that the contribution document says not to do that... sorry, I'll be more careful.

File: bash_it.sh (hunk 1 above)
[the remark this answers is not in the document]
Comment (gaelicWizard) [reply bash_it.sh]: I've just added a slight improvement to this, but I don't think it can be made better without reintroducing the original problem. We can't assign a glob to a variable...unless we adopt the wild compgen-sort from reloader.bash...which I alsö just fixed...

If you want to do that, then I'd say it needs to be a helper function and should be on a separate PR. This one is just to fix the quoting.

File: scripts/reloader.bash [hunk 2]
```diff
@@ -19,23 +19,30 @@ if [[ "$1" != "skip" ]] && [[ -d "$BASH_IT/enabled" ]]; then
       _log_debug "Loading all enabled components..." ;;
   esac
 
-  for _bash_it_config_file in $(sort <(compgen -G "$BASH_IT/enabled/*${_bash_it_config_type}.bash")); do
```
Comment (gaelicWizard) [inline scripts/reloader.bash:22]: I'm extremely curious why this construct is here in the first place. Why use compgen to glob the file path, then sort it? I assume this is something to do with ensuring that files are loaded in alphabetical order (priority number before the ---), but...isn't that true with normal globbing?

File: bash_it.sh [hunk 3]
```diff
@@ -109,19 +108,18 @@ done
 # Custom
 BASH_IT_LOG_PREFIX="core: main: "
 _log_debug "Loading general custom files..."
-CUSTOM="${BASH_IT_CUSTOM:=${BASH_IT}/custom}/*.bash ${BASH_IT_CUSTOM:=${BASH_IT}/custom}/**/*.bash"
-for _bash_it_config_file in $CUSTOM; do
+for _bash_it_config_file in "${BASH_IT_CUSTOM:=${BASH_IT}/custom}"/*.bash "${BASH_IT_CUSTOM}"/**/*.bash; do
```
Comment (davidpfarrell) [inline bash_it.sh:111]: Although it's quite clever, I feel its bad practice to hide a default assignment (and immediate re-use) in the middle of a complex statement like this.

You're going to want to either add a clarifying comment so the next dev to review this code won't miss the defaulting assignment, or you can use the logic from my original suggestion:
```
CUSTOM="${BASH_IT_CUSTOM:=${BASH_IT}/custom}"
for _bash_it_config_file in "${CUSTOM}"/*.bash "${CUSTOM}"/**/*.bash; do
```
I prefer my technique as its more clear and matches custom var/default assignment patterns used throughout the framework (ie in themes)

I'm traveling so don't have time review the newer additions to this PR yet, but will try to have a look within the next week.

Thanks !

Comment (gaelicWizard) [reply bash_it.sh:111]: Yes, this is fair. I'll update my patch.

**Comment by gaelicWizard** [comment]
Would someone do me the solid of enabling the tests to run for this PR? My main branch is so far ahead of this that I'd just like to see that BATS approves of my code. 😃

**Review by NoahGorny — APPROVED** [review]
Hi @gaelicWizard 
I have been going through your PRs and wow- you did quite a lot of great quality changes!

Thank you for your efforts, and like always thanks @davidpfarrell for your thoughtful CR.
I am also sorry that I was not quite available in the last few months. I will try to have more time to look at things- considering the effort you put in :smile:

**Comment by gaelicWizard** [comment]
Anything else needed for this PR? 😃

**Comment by NoahGorny** [comment]
hi @gaelicWizard, seems like you need to `shfmt` your changes.
Also @davidpfarrell should take another look and change his review

**Comment by gaelicWizard** [comment]
I've marked this PR as draft as I'm rebasing it on a different branch in my repo.

**Comment by gaelicWizard** [comment]
I'm closing this PR as it's been entirely replaced by just linting/`shellcheck`, which is in PR #1917.

**Comment by gaelicWizard** [comment]
> I'm closing this PR as it's been entirely replaced by just linting/`shellcheck`, which is in PR #1917.

I'm reopening this PR because my `shellcheck` PRs have still not been merged. This PR has very simple fixes to `bash_it.sh`.

**Review by NoahGorny — APPROVED** [review]
LGTM

**Comment by gaelicWizard** [comment]
Rebased on current master and ready to go!

**Comment by NoahGorny** [comment]
Hi @davidpfarrell, wanna take another look?
